Repository Ethan-Johnson17/meal_master_fullstack, pull requests merged in 2023-06, with the labels that each got.

#4 Pb ingredients db setup controller service
  README.md
  meal-master-fullstack/Controllers/IngredientsController.cs
  meal-master-fullstack/Models/Ingredient.cs
  meal-master-fullstack/Repositories/IngredientsRepository.cs
  meal-master-fullstack/Services/IngredientsService.cs
  meal-master-fullstack/Startup.cs
  meal-master-fullstack/dbSetup.sql
Labels: Backend, Req'd Addition, Blocking

#7 Init
  meal_master_fullstack.client/.gitignore
  meal_master_fullstack.client/src/App.jsx
  meal_master_fullstack.client/src/AppState.js
  meal_master_fullstack.client/src/Router.jsx
  meal_master_fullstack.client/src/assets/img/fried-rice.jpg
  meal_master_fullstack.client/src/assets/img/hamburger.jpg
  meal_master_fullstack.client/src/assets/img/hamburger.svg
  meal_master_fullstack.client/src/assets/img/pizza.jpg
  meal_master_fullstack.client/src/assets/img/steak.jpg
  meal_master_fullstack.client/src/assets/scss/main.scss
  meal_master_fullstack.client/src/components/Footer.jsx
  meal_master_fullstack.client/src/components/Navbar.jsx
  meal_master_fullstack.client/src/components/RecipeForm.jsx
  meal_master_fullstack.client/src/components/RecipeOffcanvas.jsx
  meal_master_fullstack.client/src/env.js
  meal_master_fullstack.client/src/pages/FindRecipesPage.jsx
  meal_master_fullstack.client/src/pages/HomePage.jsx
  meal_master_fullstack.client/src/services/RecipesService.js
  meal_master_fullstack.code-workspace
  meal_master_fullstack/Controllers/IngredientsController.cs
  meal_master_fullstack/Controllers/RecipesController.cs
  meal_master_fullstack/Models/Ingredient.cs
  meal_master_fullstack/Models/Recipe.cs
  meal_master_fullstack/Repositories/IngredientsRepository.cs
  meal_master_fullstack/Repositories/RecipesRepository.cs
  meal_master_fullstack/Services/IngredientsService.cs
  meal_master_fullstack/Services/RecipesServices.cs
  meal_master_fullstack/Startup.cs
  meal_master_fullstack/dbSetup.sql
Labels: Frontend, Backend

#8 Recipes added via frontend
  meal_master_fullstack.client/index.html
  meal_master_fullstack.client/src/assets/scss/_variables.scss
  meal_master_fullstack.client/src/assets/scss/main.scss
  meal_master_fullstack.client/src/components/Footer.jsx
  meal_master_fullstack.client/src/components/Login.jsx
  meal_master_fullstack.client/src/components/RecipeForm.jsx
  meal_master_fullstack.client/src/components/RecipeOffcanvas.jsx
  meal_master_fullstack.client/src/env.js
  meal_master_fullstack.client/src/pages/FindRecipesPage.jsx
  meal_master_fullstack.client/src/services/RecipesService.js
  meal_master_fullstack/dbSetup.sql
Labels: Frontend, Req'd Addition

#10 Ts shopping list backend
  .vscode/launch.json
  .vscode/tasks.json
  meal_master_fullstack/Controllers/AccountController.cs
  meal_master_fullstack/Controllers/ShoppingListItemsController.cs
  meal_master_fullstack/Models/ShoppingListItem.cs
  meal_master_fullstack/Repositories/ShoppingListItemsRepository.cs
  meal_master_fullstack/Services/ShoppingListItemsService.cs
  meal_master_fullstack/Services/ShoppingListsServiceItem.cs
  meal_master_fullstack/Startup.cs
  meal_master_fullstack/dbSetup.sql
Labels: Backend
